/**
 * offMarketScoring.ts
 *
 * Off-market lead scoring and report generation for Georgia Land Finder.
 *
 * Exports (public API – do not remove or rename):
 *   - OffMarketScoreInput    (interface)
 *   - OffMarketScoreResult   (interface)
 *   - OffMarketReport        (interface)
 *   - calculateOffMarketScore(input) → OffMarketScoreResult
 *   - generateOffMarketReport(input, parcelId?) → OffMarketReport
 *
 * All scores are integers clamped to [0, 100].
 */

// ─── Interfaces ───────────────────────────────────────────────────────────────

/** Input signals for off-market lead scoring. All fields are optional. */
export interface OffMarketScoreInput {
  // ── Original fields (do not remove) ────────────────────────────────────
  /** Parcel shows no structure or improvement value ≤ $1K. */
  likelyVacant?: boolean;
  /** Improvement value is below $5K relative to total assessment. */
  lowImprovementValue?: boolean;
  /** Owned by a government entity or public authority (surplus candidate). */
  publiclyOwned?: boolean;
  /** Property is on county delinquent tax rolls. */
  taxDelinquent?: boolean;
  /** Owner mailing address does not match the property situs address. */
  absenteeOwner?: boolean;
  /** Parcel is adjacent to or within 500 ft of a land bank property. */
  landBankAdjacent?: boolean;
  /** Within 1 mile of another tracked off-market opportunity. */
  nearExistingOpportunity?: boolean;
  /** Total parcel acreage. */
  acreage?: number;
  /** Zoning is compatible with target use (AG, RR, Timber, I-1, etc.). */
  zoningFit?: boolean;
  /**
   * Data source reliability score (0–100).
   * ≥80 = high confidence; <40 applies a global penalty.
   */
  sourceConfidence?: number;
  /** Days since the source data was last verified. */
  dataFreshnessDays?: number;

  // ── Enhanced / new optional fields ─────────────────────────────────────
  /**
   * Owner is a small LLC or trust entity.
   * Small corporate entities are often more motivated to sell than individuals.
   */
  corporateOwner?: boolean;
  /**
   * Parcel is within 0.5 mile of a major highway interchange or transit line.
   * Indicates strong future demand potential.
   */
  nearTransitCorridor?: boolean;
  /**
   * Parcel is within a federally designated Opportunity Zone.
   * Increases investor interest and off-market acquisition likelihood.
   */
  opportunityZone?: boolean;
  /**
   * Parcel has a formal blight designation from the municipality.
   * Signals distress and potential city-motivated disposition.
   */
  blightStatus?: boolean;
  /**
   * Active redevelopment is occurring on an adjacent parcel.
   * Signals rising land values and motivated holdout sellers.
   */
  adjacentRedevActivity?: boolean;
  /**
   * Number of years since the last recorded deed transfer.
   * ≥15 years is a strong motivation signal (long-hold, estate risk).
   */
  lastSaleAgeYears?: number;
  /**
   * Number of active land listings within ~5-mile radius.
   * Used for market context in report generation.
   */
  nearbyListingCount?: number;
  /**
   * County assessor's assessed value per acre (USD).
   * Used for value benchmarking in the report.
   */
  assessedValuePerAcre?: number;
  /**
   * Total active land listing count in the surrounding county market.
   * Used for liquidity context in the report.
   */
  marketListingsNearby?: number;
}

/**
 * Result of the off-market scoring calculation.
 * @see calculateOffMarketScore
 */
export interface OffMarketScoreResult {
  /** Composite off-market confidence score (0–100). */
  score: number;
  /** Human-readable strings explaining which signals fired. */
  reasons: string[];
}

/**
 * Confidence tier label for an off-market parcel.
 *
 * | Tier        | Score     | Recommended Action                      |
 * |-------------|-----------|----------------------------------------|
 * | Platinum    | 80–100    | Immediate outreach within 24 hrs        |
 * | Gold        | 65–79     | Outreach within 7 days                  |
 * | Silver      | 45–64     | Batch mail campaign within 30 days      |
 * | Bronze      | 25–44     | Monitor; re-evaluate in 90 days         |
 * | Unqualified | 0–24      | Enrich data before any contact          |
 */
export type OffMarketConfidenceTier =
  | 'Platinum'
  | 'Gold'
  | 'Silver'
  | 'Bronze'
  | 'Unqualified';

/**
 * Structured off-market report generated by generateOffMarketReport().
 */
export interface OffMarketReport {
  /** Optional parcel identifier for cross-referencing. */
  parcelId?: string;
  /**
   * True when 2 or more primary off-market signals are present.
   * Primary signals: likelyVacant, taxDelinquent, absenteeOwner,
   *   publiclyOwned, lowImprovementValue, lastSaleAgeYears ≥15, corporateOwner.
   */
  offMarketFlag: boolean;
  /** Composite off-market confidence score (0–100). */
  offMarketScore: number;
  /** Confidence tier classification based on score. */
  confidenceTier: OffMarketConfidenceTier;
  /** Signals that contributed to the score. */
  reasons: string[];
  /**
   * Classified owner type based on available signals.
   * Values: 'individual' | 'absentee_individual' | 'small_llc' |
   *   'government' | 'unknown'
   */
  ownerType: string;
  /** Plain-language recommended action for this parcel. */
  recommendedAction: string;
  /**
   * Outreach priority level (1 = highest, 5 = lowest / data enrichment only).
   */
  outreachPriority: 1 | 2 | 3 | 4 | 5;
  /** Non-fatal warnings about data quality or missing fields. */
  dataWarnings: string[];
  /** ISO 8601 timestamp of when this report was generated. */
  scoredAt: string;
  /** Summary market context fields derived from the input. */
  marketContext: {
    nearbyListingCount?: number;
    assessedValuePerAcre?: number;
    marketListingsNearby?: number;
    nearTransitCorridor: boolean;
    opportunityZone: boolean;
  };
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function clampScore(score: number): number {
  return Math.max(0, Math.min(100, Math.round(score)));
}

function toConfidenceTier(score: number): OffMarketConfidenceTier {
  if (score >= 80) return 'Platinum';
  if (score >= 65) return 'Gold';
  if (score >= 45) return 'Silver';
  if (score >= 25) return 'Bronze';
  return 'Unqualified';
}

function toRecommendedAction(tier: OffMarketConfidenceTier): string {
  switch (tier) {
    case 'Platinum':
      return 'Immediate outreach: skip-trace owner and call within 24 hours; send certified mail.';
    case 'Gold':
      return 'High-priority outreach: send direct mail and phone within 7 days.';
    case 'Silver':
      return 'Batch outreach: include in next direct mail campaign within 30 days.';
    case 'Bronze':
      return 'Monitor: add to watch list and re-evaluate in 90 days.';
    case 'Unqualified':
      return 'Enrich data: gather more signals before initiating any owner contact.';
  }
}

function toOutreachPriority(tier: OffMarketConfidenceTier): 1 | 2 | 3 | 4 | 5 {
  switch (tier) {
    case 'Platinum': return 1;
    case 'Gold':     return 2;
    case 'Silver':   return 3;
    case 'Bronze':   return 4;
    case 'Unqualified': return 5;
  }
}

function classifyOwnerType(input: OffMarketScoreInput): string {
  if (input.publiclyOwned) return 'government';
  if (input.corporateOwner) return 'small_llc';
  if (input.absenteeOwner) return 'absentee_individual';
  if (
    input.likelyVacant !== undefined ||
    input.taxDelinquent !== undefined ||
    input.zoningFit !== undefined
  ) {
    return 'individual';
  }
  return 'unknown';
}

/** Count how many primary off-market signals are active. */
function countPrimarySignals(input: OffMarketScoreInput): number {
  let count = 0;
  if (input.likelyVacant)        count++;
  if (input.taxDelinquent)       count++;
  if (input.absenteeOwner)       count++;
  if (input.publiclyOwned)       count++;
  if (input.lowImprovementValue) count++;
  if (input.corporateOwner)      count++;
  if (typeof input.lastSaleAgeYears === 'number' && input.lastSaleAgeYears >= 15) count++;
  return count;
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Calculates a composite off-market confidence score for a parcel.
 *
 * The score reflects how likely it is that:
 * 1. The parcel is NOT currently listed on MLS, and
 * 2. The owner may be motivated, reachable, and willing to sell.
 *
 * Higher score = stronger off-market lead signal.
 *
 * @param input - Off-market signal inputs (all fields optional)
 * @returns OffMarketScoreResult with score (0–100) and reasons array
 */
export function calculateOffMarketScore(input: OffMarketScoreInput): OffMarketScoreResult {
  let score = 0;
  const reasons: string[] = [];

  const add = (points: number, reason: string) => {
    score += points;
    reasons.push(reason);
  };

  // ── Original scoring signals (unchanged) ────────────────────────────────
  if (input.likelyVacant)        add(18, 'Likely vacant or land-only parcel');
  if (input.lowImprovementValue) add(14, 'Low improvement value');
  if (input.publiclyOwned)       add(12, 'Public ownership signal');
  if (input.taxDelinquent)       add(14, 'Tax delinquency signal');
  if (input.absenteeOwner)       add(10, 'Absentee owner signal');
  if (input.landBankAdjacent)    add(8,  'Adjacent/near land bank property');
  if (input.nearExistingOpportunity) add(8, 'Near existing tracked opportunity');
  if (input.zoningFit)           add(8,  'Zoning appears compatible with target use');

  if (typeof input.acreage === 'number' && input.acreage >= 0.1) {
    add(Math.min(8, input.acreage), 'Usable acreage signal');
  }

  const confidence = input.sourceConfidence ?? 50;
  if (confidence >= 80) add(8, 'High source confidence');
  else if (confidence < 40) score -= 10;

  if (typeof input.dataFreshnessDays === 'number') {
    if (input.dataFreshnessDays <= 30) add(5, 'Fresh source data');
    if (input.dataFreshnessDays > 180) score -= 8;
  }

  // ── Enhanced scoring signals ────────────────────────────────────────────
  if (input.corporateOwner)       add(6,  'Corporate/LLC owner – often motivated sellers');
  if (input.blightStatus)         add(6,  'Formal blight designation – distress signal');
  if (input.adjacentRedevActivity) add(5, 'Adjacent redevelopment activity – holdout seller opportunity');
  if (input.nearTransitCorridor)  add(5,  'Near major transit corridor – high future demand');
  if (input.opportunityZone)      add(5,  'Within federal Opportunity Zone – investor interest');

  if (typeof input.lastSaleAgeYears === 'number') {
    if (input.lastSaleAgeYears >= 15) {
      add(8, `Long hold period (${input.lastSaleAgeYears} years since last sale) – owner may be motivated`);
    } else if (input.lastSaleAgeYears >= 7) {
      add(3, `Moderate hold period (${input.lastSaleAgeYears} years since last sale)`);
    }
  }

  const finalScore = clampScore(score);
  return {
    score: finalScore,
    reasons: reasons.length ? reasons : ['Insufficient signals – Needs verification'],
  };
}

/**
 * Generates a structured off-market report for a parcel.
 *
 * This function calls calculateOffMarketScore() internally and wraps the
 * result with additional context: confidence tier, owner type, recommended
 * outreach action, priority level, market context fields, and a timestamp.
 *
 * Use this function when you need a rich report object for display or
 * downstream processing.  Use calculateOffMarketScore() directly when you
 * only need the raw numeric score.
 *
 * @param input     - OffMarketScoreInput (same as calculateOffMarketScore)
 * @param parcelId  - Optional parcel identifier for cross-referencing
 * @returns OffMarketReport
 */
export function generateOffMarketReport(
  input: OffMarketScoreInput,
  parcelId?: string,
): OffMarketReport {
  const { score, reasons } = calculateOffMarketScore(input);
  const confidenceTier = toConfidenceTier(score);
  const dataWarnings: string[] = [];

  // Warn on low source confidence
  if ((input.sourceConfidence ?? 50) < 40) {
    dataWarnings.push('Source confidence is below 40 – treat score with caution');
  }
  // Warn on stale data
  if (typeof input.dataFreshnessDays === 'number' && input.dataFreshnessDays > 180) {
    dataWarnings.push(`Data is ${input.dataFreshnessDays} days old – refresh before outreach`);
  }
  // Warn on no key signals
  if (score < 25) {
    dataWarnings.push('Score is below 25 – enrich with vacancy, ownership, and tax data before contacting owner');
  }
  // Warn on missing acreage
  if (input.acreage === undefined || input.acreage === null) {
    dataWarnings.push('Acreage not provided – confirm parcel size before outreach');
  }

  return {
    parcelId,
    offMarketFlag: countPrimarySignals(input) >= 2,
    offMarketScore: score,
    confidenceTier,
    reasons,
    ownerType: classifyOwnerType(input),
    recommendedAction: toRecommendedAction(confidenceTier),
    outreachPriority: toOutreachPriority(confidenceTier),
    dataWarnings,
    scoredAt: new Date().toISOString(),
    marketContext: {
      nearbyListingCount:    input.nearbyListingCount,
      assessedValuePerAcre:  input.assessedValuePerAcre,
      marketListingsNearby:  input.marketListingsNearby,
      nearTransitCorridor:   input.nearTransitCorridor ?? false,
      opportunityZone:       input.opportunityZone ?? false,
    },
  };
}
